kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: alpine
    commands:
    - 2=8

  - name: deploy
    image: alpine
    commands:
      - echo deploiement en cours
      - echo deploiement fin
  