version: "3"
services:
  drone-server:
    image: drone/drone
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - /var/lib/drone:/data 
    networks:
      - drone_network
    environment:
      - DRONE_GITHUB_CLIENT_SECRET=ae0c2b1252d648efa3777136c76c43732ce2ea89
      - DRONE_GITHUB_CLIENT_ID=5164e8fd7d102468e973
      - DRONE_SERVER_HOST=2748-185-146-220-82.ngrok.io
      - DRONE_SERVER_PROTO=https
      - DRONE_RPC_SECRET=bfdbe03f89c65046eace229ab756f1eb
      - "DRONE_TLS_AUTOCERT=false"
  
  drone-runner:
    image: drone/drone-runner-docker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - drone_network
    environment:
      - DRONE_RPC_HOST=2748-185-146-220-82.ngrok.io
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_SECRET=bfdbe03f89c65046eace229ab756f1eb
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=my-first-runner

networks:
  drone_network:
